# Generated by Django 5.2.17 on 2026-09-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('login', 'login'), ('login_failed', 'login_failed'), ('login_locked', 'login_locked'), ('denied', 'denied'), ('flag_created', 'flag_created'), ('flag_note_added', 'flag_note_added'), ('intervention_recorded', 'intervention_recorded'), ('outcome_recorded', 'outcome_recorded'), ('upload_accepted', 'upload_accepted'), ('upload_rejected', 'upload_rejected'), ('rebuild_started', 'rebuild_started'), ('rebuild_completed', 'rebuild_completed'), ('retrain_started', 'retrain_started'), ('retrain_completed', 'retrain_completed'), ('retrain_failed', 'retrain_failed'), ('export', 'export')], max_length=40)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_6e3b89_idx'), models.Index(fields=['action'], name='audit_audit_action_0000ce_idx')],
            },
        ),
    ]
