# Generated by Django 5.2.17 on 2026-09-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_week', models.IntegerField()),
                ('feature_set', models.CharField(choices=[('D', 'Demographic'), ('A', 'Assessment'), ('E', 'Engagement'), ('All', 'All')], max_length=20)),
                ('classifier', models.CharField(choices=[('majority', 'Majority baseline'), ('logreg', 'Logistic regression'), ('rf', 'Random forest'), ('hgb', 'Histogram gradient boosting')], max_length=40)),
                ('auc_roc', models.FloatField()),
                ('auc_pr', models.FloatField()),
                ('brier', models.FloatField()),
                ('recall_at_p50', models.FloatField()),
                ('subgroup_metrics', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=255)),
                ('training_rows', models.IntegerField()),
                ('test_rows', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['horizon_week', 'is_current'], name='scoring_mod_horizon_6edcf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('top_features', models.JSONField(blank=True, default=list)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='scoring.modelversion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='cohorts.student')),
            ],
            options={
                'ordering': ['-probability'],
                'indexes': [models.Index(fields=['model_version', '-probability'], name='scoring_ris_model_v_cf64a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'model_version'), name='uniq_risk_score')],
            },
        ),
    ]
