# Generated by Django 5.2.17 on 2026-09-12 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=3)),
                ('code_presentation', models.CharField(max_length=5)),
                ('start_date', models.DateField()),
                ('length_days', models.IntegerField()),
            ],
            options={
                'ordering': ['code_module', 'code_presentation'],
                'constraints': [models.UniqueConstraint(fields=('code_module', 'code_presentation'), name='uniq_presentation')],
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=60)),
                ('checksum', models.CharField(max_length=64)),
                ('row_count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('superseded', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', 'filename'],
                'indexes': [models.Index(fields=['batch_id', 'superseded'], name='cohorts_dat_batch_i_39124b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('region', models.CharField(max_length=40)),
                ('highest_education', models.CharField(max_length=40)),
                ('imd_band', models.CharField(blank=True, max_length=10, null=True)),
                ('age_band', models.CharField(max_length=10)),
                ('disability', models.BooleanField()),
                ('num_prev_attempts', models.IntegerField()),
                ('studied_credits', models.IntegerField()),
                ('date_registration', models.IntegerField(blank=True, null=True)),
                ('date_unregistration', models.IntegerField(blank=True, null=True)),
                ('final_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Withdrawn', 'Withdrawn'), ('Distinction', 'Distinction')], max_length=12)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='cohorts.presentation')),
            ],
            options={
                'ordering': ['presentation', 'id_student'],
                'indexes': [models.Index(fields=['presentation', 'id_student'], name='cohorts_stu_present_3b5a55_idx')],
                'constraints': [models.UniqueConstraint(fields=('presentation', 'id_student'), name='uniq_student_registration')],
            },
        ),
    ]
