# Generated by Django 5.2.17 on 2026-09-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('total_clicks', models.IntegerField(default=0)),
                ('active_days', models.IntegerField(default=0)),
                ('clicks_per_active_day', models.FloatField(default=0.0)),
                ('days_since_last_activity', models.IntegerField(default=0)),
                ('assessments_submitted', models.IntegerField(default=0)),
                ('assessments_late', models.IntegerField(default=0)),
                ('mean_score', models.FloatField(blank=True, null=True)),
                ('weighted_score_to_date', models.FloatField(blank=True, null=True)),
                ('activity_type_shares', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_features', to='cohorts.student')),
            ],
            options={
                'verbose_name_plural': 'weekly features',
                'ordering': ['student', 'week'],
                'indexes': [models.Index(fields=['student', 'week'], name='features_we_student_fb0000_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'week'), name='uniq_weekly_features')],
            },
        ),
    ]
